# pyproject.toml

[tool.black]
line-length = 88
target-version = ['py310']

[tool.ruff]
line-length = 88

# Enable Pyflakes (F) and pycodestyle (E, W) and isort (I) rules
select = ["E", "F", "W", "I"]
ignore = []

# Allow unused variables in __init__.py
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.format]
quote-style = "double"
